/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ibms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mihir Zalavadiya
 */

public class AddSupplier extends javax.swing.JFrame {

    
    Connection conn=null;
    PreparedStatement pst=null;
    String companyname,name,mobileno,email,address,gstno;
    Statement st;
    private Vector<Vector<String>> data;
    private Vector<String> header;
    public static final String DATE_FORMAT_NOW = "yyyy-MM-dd HH:mm:ss";
    Calendar cal; 
    
    public AddSupplier() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(AddSupplier.DISPOSE_ON_CLOSE);
        setVisible(true);
        cal = Calendar.getInstance();
        initJtable();
        
        lblcompanyid.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcompaney_name = new javax.swing.JTextField();
        lblcompany_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcontact_person_name = new javax.swing.JTextField();
        lblcontact_person_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcontact_number = new javax.swing.JTextField();
        lblcontact_number = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcompany_email = new javax.swing.JTextField();
        lblcompany_email = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcompany_address = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtcompany_gstno = new javax.swing.JTextField();
        btncompany_save = new javax.swing.JButton();
        btncompany_update = new javax.swing.JButton();
        btncompany_clear = new javax.swing.JButton();
        btncompany_exit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        companytable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblcompany_address = new javax.swing.JLabel();
        lblcompanyid = new javax.swing.JLabel();
        lblcontact_gstno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Company Name");

        txtcompaney_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompaney_nameActionPerformed(evt);
            }
        });
        txtcompaney_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcompaney_nameKeyReleased(evt);
            }
        });

        lblcompany_name.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("Contact Person Name");

        txtcontact_person_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontact_person_nameActionPerformed(evt);
            }
        });
        txtcontact_person_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontact_person_nameKeyReleased(evt);
            }
        });

        lblcontact_person_name.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setText("Contact Number");

        txtcontact_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontact_numberActionPerformed(evt);
            }
        });
        txtcontact_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontact_numberKeyReleased(evt);
            }
        });

        lblcontact_number.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setText("Email");

        txtcompany_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompany_emailActionPerformed(evt);
            }
        });
        txtcompany_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcompany_emailKeyReleased(evt);
            }
        });

        lblcompany_email.setForeground(new java.awt.Color(255, 0, 0));

        jLabel5.setText("Address");

        txtcompany_address.setColumns(20);
        txtcompany_address.setRows(5);
        txtcompany_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcompany_addressKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtcompany_address);

        jLabel6.setText("GST Number");

        txtcompany_gstno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcompany_gstnoKeyReleased(evt);
            }
        });

        btncompany_save.setText("Save");
        btncompany_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompany_saveActionPerformed(evt);
            }
        });
        btncompany_save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncompany_saveKeyPressed(evt);
            }
        });

        btncompany_update.setText("Update");
        btncompany_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompany_updateActionPerformed(evt);
            }
        });
        btncompany_update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncompany_updateKeyPressed(evt);
            }
        });

        btncompany_clear.setText("Clear");
        btncompany_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompany_clearActionPerformed(evt);
            }
        });
        btncompany_clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncompany_clearKeyPressed(evt);
            }
        });

        btncompany_exit.setText("Exit");
        btncompany_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompany_exitActionPerformed(evt);
            }
        });
        btncompany_exit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncompany_exitKeyPressed(evt);
            }
        });

        companytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        companytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companytableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(companytable);

        jLabel7.setText("Company Name List");

        lblcompany_address.setForeground(new java.awt.Color(255, 0, 0));

        lblcompanyid.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N

        lblcontact_gstno.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtcompany_email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtcontact_number, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtcontact_person_name, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtcompaney_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                .addComponent(lblcompany_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblcontact_person_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel3))
                                        .addComponent(lblcontact_number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4))
                                .addComponent(lblcompany_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addComponent(jLabel6)
                        .addComponent(txtcompany_gstno)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btncompany_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btncompany_save, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btncompany_update)
                                .addComponent(btncompany_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22))
                        .addComponent(lblcompany_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcontact_gstno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblcompanyid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcompaney_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcompany_name, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcontact_person_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcontact_person_name, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcontact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcontact_number, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcompany_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcompany_email, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcompany_address, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcompany_gstno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcontact_gstno, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncompany_save)
                            .addComponent(btncompany_update))
                        .addGap(4, 4, 4)
                        .addComponent(lblcompanyid, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncompany_clear)
                            .addComponent(btncompany_exit)))
                    .addComponent(jScrollPane2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcompaney_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompaney_nameActionPerformed
        
    }//GEN-LAST:event_txtcompaney_nameActionPerformed

    private void txtcontact_person_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontact_person_nameActionPerformed
        
    }//GEN-LAST:event_txtcontact_person_nameActionPerformed

    private void txtcontact_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontact_numberActionPerformed
    
    }//GEN-LAST:event_txtcontact_numberActionPerformed

    private void txtcompany_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompany_emailActionPerformed
    
    }//GEN-LAST:event_txtcompany_emailActionPerformed

    private void txtcompaney_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompaney_nameKeyReleased
        String PATTERN = "^[A-Za-z]{0,50}[ A-Za-z]{0,50}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtcompaney_name.getText());
        if(!match.matches())
        {
            lblcompany_name.setText("Name is Incorrect");
        }
        else
        {
            lblcompany_name.setText("");
        }
    }//GEN-LAST:event_txtcompaney_nameKeyReleased

    private void txtcontact_person_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontact_person_nameKeyReleased
        String PATTERN = "^[A-Za-z]{0,50}[ A-Za-z]{0,50}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtcontact_person_name.getText());
        if(!match.matches())
        {
            lblcontact_person_name.setText("Name is Incorrect");
        }
        else
        {
            lblcontact_person_name.setText("");
        }
    }//GEN-LAST:event_txtcontact_person_nameKeyReleased

    private void txtcontact_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontact_numberKeyReleased
        String PATTERN = "^[0-9]{10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtcontact_number.getText());
        if(!match.matches())
        {
            lblcontact_number.setText("Contact Number is Incorrect");
        }
        else
        {
            lblcontact_number.setText("");
        }
    }//GEN-LAST:event_txtcontact_numberKeyReleased

    private void txtcompany_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompany_emailKeyReleased
        String PATTERN = "^[A-Za-z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtcompany_email.getText());
        if(!match.matches())
        {
            lblcompany_email.setText("Email is Incorrect");
        }
        else
        {
            lblcompany_email.setText("");
        }
    }//GEN-LAST:event_txtcompany_emailKeyReleased

    private void txtcompany_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompany_addressKeyReleased
        String PATTERN = "^[A-Za-z0-9]{0,50}[ A-Za-z0-9,-]{0,50}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtcompany_address.getText());
        if(!match.matches())
        {
            lblcompany_address.setText("Address is Incorrect");
        }
        else
        {
            lblcompany_address.setText("");
        }   
    }//GEN-LAST:event_txtcompany_addressKeyReleased

    private void txtcompany_gstnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompany_gstnoKeyReleased
        String PATTERN = "^[0-9]{2}[A-Z0-9]{10}[1][Z][5]$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtcompany_gstno.getText());
        if(!match.matches())
        {
            lblcontact_gstno.setText("Address is Incorrect");
        }
        else
        {
            lblcontact_gstno.setText("");
        }  
    }//GEN-LAST:event_txtcompany_gstnoKeyReleased

    //clear
    private void btncompany_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompany_clearActionPerformed
        clear();
    }//GEN-LAST:event_btncompany_clearActionPerformed

    //exit
    private void btncompany_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompany_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncompany_exitActionPerformed

    //save
    private void btncompany_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompany_saveActionPerformed
        save();
    }//GEN-LAST:event_btncompany_saveActionPerformed

    private void companytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companytableMouseClicked
        try
        {
            btncompany_save.setEnabled(false);
            btncompany_update.setEnabled(true);
           
            int r= companytable.getSelectedRow();
            int c=companytable.getSelectedColumn();
            Object s=companytable.getValueAt(r, 0);
            String NameVal = s.toString();
            ResultSet rs = st.executeQuery("select * from Supplier where Company_Name='"+NameVal+"'");
            rs.next();
            lblcompanyid.setText(""+rs.getInt("Supplier_ID"));
            txtcompaney_name.setText(""+rs.getString("Company_Name"));
            txtcompany_address.setText(""+rs.getString("Address"));
            txtcontact_number.setText(""+rs.getString("Phone_Number"));
            txtcompany_email.setText(""+rs.getString("Email"));
            txtcontact_person_name.setText(""+rs.getString("Contact_Person_Name"));
            txtcompany_gstno.setText(""+rs.getString("Gst_No"));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_companytableMouseClicked

    //update
    private void btncompany_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompany_updateActionPerformed
        update();
    }//GEN-LAST:event_btncompany_updateActionPerformed

    //save key pressed
    private void btncompany_saveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncompany_saveKeyPressed
        save();
    }//GEN-LAST:event_btncompany_saveKeyPressed

    //update key pressed
    private void btncompany_updateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncompany_updateKeyPressed
        update();
    }//GEN-LAST:event_btncompany_updateKeyPressed

    private void btncompany_clearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncompany_clearKeyPressed
        clear();
    }//GEN-LAST:event_btncompany_clearKeyPressed

    private void btncompany_exitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncompany_exitKeyPressed
        this.dispose();
    }//GEN-LAST:event_btncompany_exitKeyPressed

    private void save()
    {
        try
        {
            companyname = txtcompaney_name.getText();
            name = txtcontact_person_name.getText();
            mobileno = txtcontact_number.getText();
            email = txtcompany_email.getText();
            address = txtcompany_address.getText();
            gstno = txtcompany_gstno.getText();
            
            if(companyname.isEmpty()||name.isEmpty()||mobileno.isEmpty()||email.isEmpty()||address.isEmpty()||gstno.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please Enter above fild");
            }
            else if(!companyname.isEmpty() && !name.isEmpty() && !mobileno.isEmpty() && !email.isEmpty() && !address.isEmpty() && !gstno.isEmpty())
            {
                conn = DriverManager.getConnection("jdbc:ucanaccess://G:\\Mydb.accdb");
                
                pst = conn.prepareStatement("INSERT into Supplier(Company_Name,Address,Phone_Number,Email,Contact_Person_Name,Gst_No,Created_Date_Time,Updated_Date_Time) VALUES(?,?,?,?,?,?,?,?)");
                
                pst.setString(1, txtcompaney_name.getText());                
                pst.setString(2, txtcompany_address.getText());                
                pst.setString(3, txtcontact_number.getText());
                pst.setString(4, txtcompany_email.getText());
                pst.setString(5, txtcontact_person_name.getText());
                pst.setString(6, txtcompany_gstno.getText());
                pst.setDate(7, new Date(cal.getTimeInMillis()));
                pst.setDate(8, new Date(cal.getTimeInMillis()));
                
                pst.executeUpdate();
                
                conn.commit();
                conn.close();                
                
                JOptionPane.showMessageDialog(null,"Successfully Inserted");
                
                initJtable();
                
                txtcompaney_name.setText("");
                txtcontact_person_name.setText("");
                txtcontact_number.setText("");
                txtcompany_email.setText("");
                txtcompany_address.setText("");
                txtcompany_gstno.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void update()
    {
        try 
        {   
            int id = Integer.parseInt(lblcompanyid.getText());
            conn = DriverManager.getConnection("jdbc:ucanaccess://G:\\Mydb.accdb");
            pst = conn.prepareStatement("UPDATE Supplier SET Company_Name = ?, Address = ?, Phone_Number = ?, Email = ?, Contact_Person_Name = ?, Gst_No = ?,Updated_Date_Time = ? where Supplier_ID = "+id+" ");
           
            pst.setString(1, txtcompaney_name.getText());                
            pst.setString(2, txtcompany_address.getText());                
            pst.setString(3, txtcontact_number.getText());
            pst.setString(4, txtcompany_email.getText());
            pst.setString(5, txtcontact_person_name.getText());
            pst.setString(6, txtcompany_gstno.getText());
            pst.setDate(7, new Date(cal.getTimeInMillis()));
            
            pst.executeUpdate();
            
            initJtable();
            
            txtcompaney_name.setText("");
            txtcontact_person_name.setText("");
            txtcontact_number.setText("");
            txtcompany_email.setText("");
            txtcompany_address.setText("");
            txtcompany_gstno.setText("");
            btncompany_save.setEnabled(true);
            
            //btnupdate.setEnabled(false);  
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void clear()
    {
        txtcompaney_name.setText("");
        txtcontact_person_name.setText("");
        txtcontact_number.setText("");
        txtcompany_email.setText("");
        txtcompany_address.setText("");
        txtcompany_gstno.setText("");
    }
    
    private void initJtable()
    {
        try
        {
            conn = DriverManager.getConnection("jdbc:ucanaccess://G:\\Mydb.accdb");
            st = conn.createStatement();
            
            header = new Vector<String>();
            header.add("Company Name");
            header.add("Contact Person Name");
            header.add("Contact No.");
            header.add("Email");
            header.add("Address");
            header.add("GST No.");
            
            ResultSet rs = st.executeQuery("SELECT * FROM Supplier ORDER BY Company_Name");
            data = new Vector<Vector<String>>();
            while(rs.next())
            {
                Vector<String> custVet = new Vector<String>();
                custVet.add(rs.getString("Company_Name"));
                custVet.add(rs.getString("Contact_Person_Name"));
                custVet.add(rs.getString("Phone_Number"));
                custVet.add(rs.getString("Email"));
                custVet.add(rs.getString("Address"));
                custVet.add(rs.getString("Gst_No"));
                data.add(custVet);
            }
           DefaultTableModel dtm = new DefaultTableModel(data,header);
           companytable.setModel(dtm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncompany_clear;
    private javax.swing.JButton btncompany_exit;
    private javax.swing.JButton btncompany_save;
    private javax.swing.JButton btncompany_update;
    private javax.swing.JTable companytable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcompany_address;
    private javax.swing.JLabel lblcompany_email;
    private javax.swing.JLabel lblcompany_name;
    private javax.swing.JLabel lblcompanyid;
    private javax.swing.JLabel lblcontact_gstno;
    private javax.swing.JLabel lblcontact_number;
    private javax.swing.JLabel lblcontact_person_name;
    private javax.swing.JTextField txtcompaney_name;
    private javax.swing.JTextArea txtcompany_address;
    private javax.swing.JTextField txtcompany_email;
    private javax.swing.JTextField txtcompany_gstno;
    private javax.swing.JTextField txtcontact_number;
    private javax.swing.JTextField txtcontact_person_name;
    // End of variables declaration//GEN-END:variables
}
