/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ibms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mihir Zalavadiya
 */
public class Mainform extends javax.swing.JFrame {

    Statement st;
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    //JasperReport JASP_REP = null;
    /**
     * Creates new form Mainform
     */
    public Mainform() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        
        setExtendedState(Mainform.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmibilling = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        note = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Add");

        jmibilling.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmibilling.setText("Billing");
        jmibilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmibillingActionPerformed(evt);
            }
        });
        jMenu2.add(jmibilling);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Add Customer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Add Item");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Add Category");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Add Supplier");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Settings");

        jMenuItem4.setText("Change Password");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Report");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("All Customer");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Print Bill");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Bill Receipt");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Supplier Record");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuItem8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem8KeyPressed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Category Record");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Tools");

        note.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        note.setSelected(true);
        note.setText("Calculator");
        note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteActionPerformed(evt);
            }
        });
        jMenu4.add(note);

        jCheckBoxMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Notepad");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ChangePassword cpw = new ChangePassword();
        cpw.setLocationRelativeTo(null);
        cpw.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteActionPerformed
        
        Runtime rt = Runtime.getRuntime();
        try
        {
            rt.exec("C:/Windows/System32/calc.exe");
        }
        catch(Exception e)
        {
            Logger.getLogger(Mainform.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_noteActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
        
        Runtime rt = Runtime.getRuntime();
        try{
            rt.exec("C:/Windows/System32/notepad.exe");
        }
        catch(Exception e)
        {
            Logger.getLogger(Mainform.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddCustomer acu = new AddCustomer();
        acu.setLocationRelativeTo(null);
        acu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AddItem ait = new AddItem();
        ait.setLocationRelativeTo(null);
        ait.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AddCategory aca = new AddCategory();
        aca.setLocationRelativeTo(null);
        aca.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        AddSupplier asu = new AddSupplier();
        asu.setLocationRelativeTo(null);
        asu.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jmibillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmibillingActionPerformed
        Billing bill = new Billing();
        bill.setLocationRelativeTo(null);
        bill.setVisible(true);
    }//GEN-LAST:event_jmibillingActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try
        {
            //Class.forName("com.jdbc.driver");
            conn = DriverManager.getConnection("jdbc:ucanaccess://G:\\Mydb.accdb");
            st = conn.createStatement();
            String dir = System.getProperty("user.dir");
            File f = new File(dir+"/src/ibms/AllCustomer.jrxml");

            String query = "SELECT Customer.Customer_Name AS Customer_Name, Customer.Address AS Address, Customer.Email AS Email, Customer.Mobile_No AS Mobile_No FROM Customer ORDER BY Customer.Customer_ID";

            JasperReport JASP_REP2=JasperCompileManager.compileReport(JRXmlLoader.load(f));

            JASP_REP2.setProperty("net.sf.jasperreports.xpath.executer.factory"
                ,"net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");

            ResultSet rs2 = st.executeQuery(query);
            JRResultSetDataSource  jrSource = new JRResultSetDataSource(rs2);

            JasperPrint JASP_PRINT=JasperFillManager.fillReport(JASP_REP2, null,jrSource);
            JasperViewer.viewReport(JASP_PRINT,false);
            conn.close();
        }
        catch(Exception e)
        {
            System.out.println("====="+e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem8KeyPressed
//        try
//        {
//            //Class.forName("com.jdbc.driver");
//            Connection conn = DriverManager.getConnection("jdbc:ucanaccess://G:\\Mydb.accdb");
//            Statement st = conn.createStatement();
//            String dir = System.getProperty("user.dir");
//            File f = new File(dir+"/src/ibms/Supplier.jrxml");
//
//            //String query = "SELECT Supplier.Contact_Person_Name AS Contact_Person_Name, Supplier.Company_Name AS Company_Name, Supplier.Address AS Address, Supplier.Phone_Number AS Phone_Number, Supplier.Email AS Email FROM Supplier ORDER BY Supplier.Supplier_ID";
//            String query = "SELECT Contact_Person_Name,Company_Name,Address,Phone_Number,Email FROM Supplier ORDER BY Supplier_ID";
//            JasperReport JASP_REP2=JasperCompileManager.compileReport(JRXmlLoader.load(f));
//
//            JASP_REP2.setProperty("net.sf.jasperreports.xpath.executer.factory"
//                ,"net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");
//
//            ResultSet rs2 = st.executeQuery(query);
//            JRResultSetDataSource  jrSource = new JRResultSetDataSource(rs2);
//
//            JasperPrint JASP_PRINT=JasperFillManager.fillReport(JASP_REP2, null,jrSource);
//            JasperViewer.viewReport(JASP_PRINT,false);
//        }
//        catch(Exception e)
//        {
//            System.out.println("====="+e.getMessage());
//        }
    }//GEN-LAST:event_jMenuItem8KeyPressed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try
        {
            //Class.forName("com.jdbc.driver");
            conn = DriverManager.getConnection("jdbc:ucanaccess://G:\\Mydb.accdb");
            st = conn.createStatement();
            String dir = System.getProperty("user.dir");
            File f = new File(dir+"/src/ibms/Supplier.jrxml");

            String query = "SELECT Supplier.Contact_Person_Name AS Contact_Person_Name, Supplier.Company_Name AS Company_Name, Supplier.Address AS Address, Supplier.Phone_Number AS Phone_Number, Supplier.Email AS Email FROM Supplier ORDER BY Supplier.Supplier_ID";
            //String query = "SELECT Contact_Person_Name,Company_Name,Address,Phone_Number,Email FROM Supplier ORDER BY Supplier_ID";
            JasperReport JASP_REP2=JasperCompileManager.compileReport(JRXmlLoader.load(f));

            JASP_REP2.setProperty("net.sf.jasperreports.xpath.executer.factory"
                ,"net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");

            ResultSet rs2 = st.executeQuery(query);
            JRResultSetDataSource  jrSource = new JRResultSetDataSource(rs2);

            JasperPrint JASP_PRINT=JasperFillManager.fillReport(JASP_REP2, null,jrSource);
            JasperViewer.viewReport(JASP_PRINT,false);
        }
        catch(Exception e)
        {
            System.out.println("====="+e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        try
        {
            //Class.forName("com.jdbc.driver");
            conn = DriverManager.getConnection("jdbc:ucanaccess://G:\\Mydb.accdb");
            st = conn.createStatement();
            String dir = System.getProperty("user.dir");
            File f = new File(dir+"/src/ibms/Category.jrxml");

            String query = "SELECT Category.Category_Name AS Category_Name, Category.Description AS Description FROM Category ORDER BY Category.Category_ID";
            //String query = "SELECT Contact_Person_Name,Company_Name,Address,Phone_Number,Email FROM Supplier ORDER BY Supplier_ID";
            JasperReport JASP_REP2=JasperCompileManager.compileReport(JRXmlLoader.load(f));

            JASP_REP2.setProperty("net.sf.jasperreports.xpath.executer.factory"
                ,"net.sf.jasperreports.engine.util.xml.JaxenXPathExecuterFactory");

            ResultSet rs2 = st.executeQuery(query);
            JRResultSetDataSource  jrSource = new JRResultSetDataSource(rs2);

            JasperPrint JASP_PRINT=JasperFillManager.fillReport(JASP_REP2, null,jrSource);
            JasperViewer.viewReport(JASP_PRINT,false);
        }
        catch(Exception e)
        {
            System.out.println("====="+e.getMessage());
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jmibilling;
    private javax.swing.JCheckBoxMenuItem note;
    // End of variables declaration//GEN-END:variables
}
